apiVersion : apps/v1
kind: Deployment
metadata:
  name: "aaaaatiwarishubaks-8cbd"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "aaaaatiwarishubaks-8cbd"
  template:
    metadata:
      labels:
        app: "aaaaatiwarishubaks-8cbd"
    spec:
      containers:
        - name: "aaaaatiwarishubaks-8cbd"
          image: "diaggarwregistry.azurecr.io/aaaaatiwarishubaks806b"
          ports:
          - containerPort: 8080